name: venvman CI Test

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-venvman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # ✅ Clones repo automatically

      - name: Update System Packages
        run: |
          sudo apt update
          sudo apt upgrade -y

      - name: Add deadsnakes PPA
        run: |
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt update

      - name: Install Python 3.11 and venv
        run: |
          sudo apt install -y python3.11 python3.11-venv python3.10-venv

      - name: Verify Python Installation
        run: |
          python3.11 --version
          python3.10 --version

      - name: Download and Install venvman
        run: |
          curl -sSL https://raw.githubusercontent.com/nickeisenberg/venvman/master/install.sh -o install.sh
          bash install.sh

      - name: Download and Install venvman
        run: |
          source ~/.bashrc

      - name: Run venvman Tests
        run: |
          bash tests/test_venvman.sh

